### ISSUE TITLE
Randomly I am getting errors

### ISSUE THREAD

**Issue by Vinlock** [gtache/intellij-lsp#105]
This will happen when I close the Configurations window in Goland, or commit, or push to git.

```java.lang.NullPointerException
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.stopLoggingServerErrors(LanguageServerWrapperImpl.scala:498)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.stop(LanguageServerWrapperImpl.scala:266)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.start(LanguageServerWrapperImpl.scala:354)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.connect(LanguageServerWrapperImpl.scala:172)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$2(PluginMain.scala:137)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$2$adapted(PluginMain.scala:133)
	at scala.Option.foreach(Option.scala:257)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$1(PluginMain.scala:133)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by Cypher1** [comment]
Am having the same errors with typescript-language-server (just editing and saving a file) and with my own language server.
