### ISSUE TITLE
Add ability to specify additional resolvers for coursier

### ISSUE THREAD

**Issue by ShaneDelmore** [gtache/intellij-lsp#11]
I’m tried to take this plugin for a spin today but ran into a small snag, the library I was trying to use depends on another library that is not published to one of coursier’s default resolvers.  An additional configuration column to add coursier arguments would be enough for me to pass the additional resolver to coursier and get working.

**Comment by gtache** [comment]
I've just uploaded the new release, it includes settings to add new repositories to coursier! I hope it will suit your needs.

**Comment by ShaneDelmore** [comment]
Still no luck.  I can add the same resolver to the command line coursier but it doesn't work in the plugin.

Adding the resolver works from the command line args, but doesn't seem to help using the gui.

For example this fails:
```
coursier resolve com.dhpcs:scala-json-rpc_2.12:2.0.1
```
and this succeeds
```
coursier resolve com.dhpcs:scala-json-rpc_2.12:2.0.1 -r https://dl.bintray.com/dhpcs/maven
```
Yet adding resolver 
```
maven::https://dl.bintray.com/dhpcs/maven
```
results in:
```
Couldn't fetch all dependencies
java.lang.Throwable: Couldn't fetch all dependencies
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.github.gtache.lsp.utils.coursier.CoursierImpl$.resolveClasspath(CoursierImpl.scala:50)
	at com.github.gtache.lsp.client.languageserver.serverdefinition.ArtifactLanguageServerDefinition.createConnectionProvider(ArtifactLanguageServerDefinition.scala:20)
	at com.github.gtache.lsp.client.languageserver.serverdefinition.LanguageServerDefinition.start(LanguageServerDefinition.scala:68)
	at com.github.gtache.lsp.client.languageserver.serverdefinition.LanguageServerDefinition.start$(LanguageServerDefinition.scala:63)
	at com.github.gtache.lsp.client.languageserver.serverdefinition.ArtifactLanguageServerDefinition.start(ArtifactLanguageServerDefinition.scala:15)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.start(LanguageServerWrapperImpl.scala:227)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.connect(LanguageServerWrapperImpl.scala:152)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$4(PluginMain.scala:131)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$4$adapted(PluginMain.scala:113)
	at scala.Option.foreach(Option.scala:257)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$3(PluginMain.scala:113)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gtache** [comment]
That's strange, I had the same error trying to get this dependency the first time, but the second time it worked.
Now I've updated to the latest Coursier version, cleared the cache and it worked first try, so maybe it'll be better now ?

**Comment by ShaneDelmore** [comment]
Once I clone the repo, how can I build and test the plugin?

I tried plain old sbt compile and end up with a lot of errors in HoverHandler.  For example:
```
intellij-lsp/intellij-lsp/src/com/github/gtache/lsp/requests/HoverHandler.scala:3:12: object vladsch is not a member of package com
[error] import com.vladsch.flexmark.html.HtmlRenderer

```

**Comment by gtache** [comment]
Yeah, I'm not really the one who manages the build.sbt (@smarter), and I tried to make the "sbt intellij-lsp/run" command work, but there is always a different problem (I added the missing (flexmark) dependency however). I will ask him tomorrow to look into it if possible. 
What you can do is create a project and import the source files and libraries manually, then you should be able to run the plugin. I will copy what I wrote in the other issue : 

Now, if you want to easily (except the setup) debug using IntelliJ, you can clone/download the intellij-lsp subfolder, create a new IntelliJ plugin project with the root at intellij-lsp (or copy the files to a new project location), add a new IntelliJ Platform SDK (by going into Project Structure/SDKs) pointing at the IntelliJ installation folder, add a Scala (2.12.4) SDK (by going into Project Structure/Global Libraries), add the required libraries (by going into project structure/libraries and seeing which libraries are needed by looking into the build.gradle file: it's lsp4j, coursier, coursier-cache and flexmark ; I guess you could also synchronize using Gradle), and finally launch the plugin and if everything was done correctly a sandbox should start. Now you have easy access to the log in the main IntelliJ window, you can set breakpoints in the code, etc.

**Comment by ShaneDelmore** [comment]
If I build locally I can now resolve correctly after adding additional resolvers.  The published version still does not work but I am in no rush and can build local until the next release so I will close this issue.  Thank you for your help.
