### ISSUE TITLE
Exception in plugin LSP Support (1.4.5)

### ISSUE THREAD

**Issue by PrigovorO** [gtache/intellij-lsp#131]
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.intellij.openapi.project.ProjectUtil.guessProjectDir, parameter $this$guessProjectDir
	at com.intellij.openapi.project.ProjectUtil.guessProjectDir(ProjectUtil.kt)
	at com.github.gtache.lsp.utils.FileUtils$.editorToProjectFolderPath(FileUtils.scala:153)
	at com.github.gtache.lsp.utils.FileUtils$.editorToProjectFolderUri(FileUtils.scala:149)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$1(PluginMain.scala:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gtache** [comment]
Fixed in 1.6.1
