### ISSUE TITLE
Server launch causes java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by jeffmaury** [gtache/intellij-lsp#140]
Installed the latest 1.6.1 and tested my Quarkus LSP (github.com/redhat-developer/intellij-quarkus).
When the server is launched, I have the following error:

```
java.lang.AbstractMethodError: com.intellij.openapi.wm.StatusBarWidget.getPresentation(Lcom/intellij/openapi/wm/StatusBarWidget$PlatformType;)Lcom/intellij/openapi/wm/StatusBarWidget$WidgetPresentation;
	at com.github.gtache.lsp.client.languageserver.LSPServerStatusWidget.getPresentation(LSPServerStatusWidget.scala:60)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.wrap(IdeStatusBarImpl.java:518)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.addWidget(IdeStatusBarImpl.java:348)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.lambda$addWidget$3(IdeStatusBarImpl.java:191)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:696)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
I am using IU-2019.1 and noticed `StatusBarWidget` does not have the empty parameter `getPresentation` method. It is there on 2019.3, so seems this plugin is not compatible with older releases.

**Comment by gtache** [comment]
That's pretty bad indeed, I've uploaded a release for earlier versions and also uploaded it on the JetBrains repository. I hope it will fix your problems.
