### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by hectorj** [gtache/intellij-lsp#141]
Hi! Just saw some exception, I'm just here to report it if it can help.

Plugin version: 1.6.1

Stacktrace:

```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$signatureHelp$1(EditorEventManager.scala:223)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Language Server: [the one from `vimeo/psalm`, v3.9.4](https://github.com/vimeo/psalm/blob/3.9.4/src/psalm-language-server.php)

Sadly I don't know what action triggered it.

**Comment by hectorj** [comment]
Forgot the IDE version: 

```
PhpStorm 2019.3.3
Build #PS-193.6494.47, built on February 12, 2020
Licensed to Hector Jusforgues
Subscription is active until July 31, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.84-microsoft-standard
GC: ParNew, ConcurrentMarkSweep
Memory: 1805M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.github.gtache.lsp, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, mobi.hsz.idea.gitignore, org.psliwa.idea.composer, ru.adelf.idea.dotenv
```

**Comment by MinDBreaK** [comment]
Still happening on PHPStorm 2020
```
PhpStorm 2020.1.2
Build #PS-201.7846.90, built on June 3, 2020
Licensed to <Name>
Subscription is active until October 7, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.github.gtache.lsp, com.intellij.ideolog, org.intellij.plugins.hcl, com.mallowigi, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, org.jetbrains.plugins.go-template, com.intellij.kubernetes, ru.adelf.idea.dotenv, lv.midiana.misc.phpstorm-plugins.deep-keys, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, de.espend.idea.php.phpunit, de.espend.idea.php.generics, rocks.blackcat.vcl
```
