### ISSUE TITLE
java.util.concurrent.CancellationException

### ISSUE THREAD

**Issue by kalvisbuls** [gtache/intellij-lsp#150]
I'm very regularly having this exception when using [Psalm](https://psalm.dev/). I've seen similar issues reported here, including several Psalm-related, but not with this particular error.

```
java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2396)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.stop(LanguageServerWrapperImpl.scala:268)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.disconnect(LanguageServerWrapperImpl.scala:261)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorClosed$2(PluginMain.scala:291)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I'm using PhpStorm 2020.1.2 (build #PS-201.7846.90) with the latest version of the plugin (1.6.1). Psalm is set up using standard configuration described [here](https://psalm.dev/docs/running_psalm/language_server/#phpstorm).

**Comment by caugner** [comment]
Same here with Psalm:

```
java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(Unknown Source)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.stop(LanguageServerWrapperImpl.scala:268)
	at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.disconnect(LanguageServerWrapperImpl.scala:261)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorClosed$2(PluginMain.scala:291)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by oliverswitzer** [comment]
Can confirm that I am getting this with using [elixir-lsp](https://github.com/elixir-lsp/elixir-ls)
