### ISSUE TITLE
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only

### ISSUE THREAD

**Issue by tekord** [gtache/intellij-lsp#59]
Hi! I tried to use D Language Server, it is new and yet not pulled feature of https://github.com/intellij-dlanguage (RR is here: https://github.com/intellij-dlanguage/intellij-dlanguage.github.io/pull/3).

I got this error when I try to use autocompete:

```
Details: Current thread: Thread[ApplicationImpl pooled thread 18,4,Idea Thread Group] 1654340627
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1585037025

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1090)
	at com.intellij.openapi.editor.impl.view.EditorView.assertIsReadAccess(EditorView.java:599)
	at com.intellij.openapi.editor.impl.view.EditorView.logicalPositionToOffset(EditorView.java:160)
	at com.intellij.openapi.editor.impl.EditorImpl.logicalPositionToOffset(EditorImpl.java:2137)
	at com.github.gtache.lsp.utils.DocumentUtils$.logicalToLSPPos(DocumentUtils.scala:49)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$onTypeFormatting$1(EditorEventManager.scala:1426)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Settings was: `executable` is path to 'dls.exe' ("D:\Dlang\dls\dls.exe"), extension is 'd' (also tried with dot '.d'), no args.

UPD. Version 1.5.0

**Comment by gtache** [comment]
Hello, that's very strange, looking at the 1.5.0 code it shouldn't happen.    
Can you check with 1.5.2 (either when it comes out via plugin update or by manually installing the release) and tell me if it still happens?

**Comment by tekord** [comment]
@gtache yeah! it works! :)

**Comment by tekord** [comment]
oh, noooo. It crashed. I updated DLS (D Language Server) to the latest version and now plugin crashed with the same error:

```

Details: Current thread: Thread[ApplicationImpl pooled thread 13,4,Idea Thread Group] 218987582
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 891034732

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1090)
	at com.intellij.openapi.editor.impl.view.EditorView.assertIsReadAccess(EditorView.java:599)
	at com.intellij.openapi.editor.impl.view.EditorView.logicalPositionToOffset(EditorView.java:160)
	at com.intellij.openapi.editor.impl.EditorImpl.logicalPositionToOffset(EditorImpl.java:2137)
	at com.github.gtache.lsp.utils.DocumentUtils$.logicalToLSPPos(DocumentUtils.scala:49)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$onTypeFormatting$1(EditorEventManager.scala:1430)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tekord** [comment]
@gtache How to reproduce:

No matter what platform version of DLS I use (x86 or x86_64), error occured when I try to call autocomplete in this code:

import std.stdio;
imp<ctrl+space>ort s<ctrl+space>td.std<ctrl+space>io:<ctrl+space>File;
<!CRASH!>

**Comment by gtache** [comment]
Oh god I'm blind, sorry you can redownload 1.5.2 and it should work

**Comment by tekord** [comment]
Seems ok now.
